.\" Manpage for pass.
.\" Contact jean.guyomarch@gmail.com to correct errors or typos.

.TH man 1 "19 October 2015" "1.1" "pass man page"
.SH NAME
pass \- password manager
.SH SYNOPSIS
pass -lfadxgrhV
.SH DESCRIPTION
pass allows you to manage your passwords in an encrypted file

Example: to add a password for a github account, let's call the key 'github_password' and let's say your github's password is '1234' (if your password is really 1234, please consider changint it):
   pass -a github_password
then enter your password '1234' (the input is masked)
then enter your cipher key. If you forget it, you cannot access your password back! It will be definitly lost!

To get your password back:
   pass -x github_password
then enter your cipher key. '1234' is now in your clipboard if you entered the right cipher key.

.SH OPTIONS

.TP
.BR \-f,--file " "\fIpath\fR
   specify the file to use at <path>
.TP
.BR \-a,--add " "\fIkey\fR
   add a password for <key>
.TP
.BR \-r,--replace " "\fIkey\fR
   replace a password for <key>. No backup is created for the old password. It will be lost!. Asks for confirmation.
.TP
.BR \-d,--delete " "\fIkey\fR
   delete the password stored for <key>. Asks for confirmation.
.TP
.BR \-g,--generate " "\fI[digits]\fR
   generates a random password using openSSL (default: 64 digits) [digits] cannot be greater than 64
.TP
.BR \-l,--list
   lists all the registered keys
.TP
.BR \-V,--version
   shows the version
.TP
.BR \-h,--help
   shows the help
.TP
.BR \-x,--extract " " \fIkey\fR
   extract the password for the key. Asks the decipher key.

.SH AUTHOR
Jean Guyomarc'h <jean.guyomarch@gmail.com>

.SH COPYRIGHT
The MIT License (MIT)

Copyright (c) 2013 - 2015 Jean Guyomarc'h

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.

