.\" Manpage for pass.
.\" Contact jean.guyomarch@gmail.com to correct errors or typos.
.TH man 1 "28 August 2013" "1.0" "pass man page"
.SH NAME
pass \- password manager
.SH SYNOPSIS
pass -[v]laxdsgrVL
.SH DESCRIPTION
pass allows you to manage your passwords in an encrypted file by assigning to a password a public key.

Example: to add a password for a github account, let's call the key 'github_password' and let's say your github's password is '1234'
   pass -a github_password
then enter your password '1234' (the input is masked)
then enter your cipher key. If you forget it, you cannot access your password back! It will be definitly lost!
   pass -x github_password
then enter your cipher key, '1234' is now in your clipboard if you entered the right cipher key
.SH OPTIONS
The -v option allows a verbose output when adding (-a) and extracting (-x) data from the encrypted file. All the data will be displayed in stdout.

.TP
.BR \-[v]a " "\fIkey\fR
   add/replace a password for <key>
.TP
.BR \-d " "\fIkey\fR
   delete the password stored for <key>. It asks confirmation but will not ask for a cipher key!
.TP
.BR \-g " "\fI[digits]\fR
   generates a random password using openSSL (default: 64 digits) [digits] cannot be greater than 64
.TP
.BR \-l
   lists all the registered keys
.TP
.BR \-L
   show the license
.TP
.BR \-r " " \fIold_key\fR " " \fInew_key\fR
   Rename a key
.TP
.BR \-s
   gives statistics about the file
.TP
.BR \-V
   shows the version
.TP
.BR \-[v]x " " \fIkey\fR
   extract the password for the key
.SH AUTHOR
Jean Guyomarc'h <jean.guyomarch@gmail.com>
.SH COPYRIGHT
The MIT License (MIT)

Copyright (c) 2013 Jean Guyomarc'h

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
